"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Issue = { id:string; icon:string; title:string; summary:string; policy:string; bullets:string[]; detail:string };
type News = { id:string; date:string; category:string; title:string; excerpt:string; body:string[] };

const nav = [
  ["Home","/"],["About Kamala","/about"],["Issues","/issues"],["Record","/record"],["News","/news"],
  ["Endorsements","/endorsements"],["Events","/events"],["Media","/media"],["Get Involved","/involved"],["Contact","/contact"]
];

const issues: Issue[] = [
  {id:"safety",icon:"⚖",title:"Public Safety and Equal Justice",summary:"Safe neighborhoods and equal treatment under law must go hand in hand.",policy:"A statewide Safe Communities Partnership that puts prevention, accountability, and local coordination first.",bullets:["Fund community policing and violence-interruption partnerships","Modernize emergency response and victim services","Set statewide standards for transparent, constitutional enforcement"],detail:"Kamala will bring prosecutors, mayors, first responders, neighborhood leaders, and civil-rights advocates to one table—measuring what works, publishing the results, and directing resources to the communities that need them most."},
  {id:"integrity",icon:"★",title:"Honest Government and Constitutional Leadership",summary:"Lincoln deserves an executive branch that follows the law and answers to the public.",policy:"Create the Lincoln Public Integrity Office with independent authority to investigate corruption and abuse.",bullets:["Publish contracts and executive meetings in a searchable portal","Protect inspectors general and whistleblowers","Require ethics and constitutional training across the cabinet"],detail:"The Harris administration will strengthen the guardrails of democracy, close pay-to-play loopholes, and make it easier for citizens to see how decisions are made and public dollars are spent."},
  {id:"jobs",icon:"↗",title:"Jobs, Industry, and Economic Opportunity",summary:"Build an economy where hard work is rewarded in every county.",policy:"Launch Lincoln Works, a ten-year industry and infrastructure strategy focused on good-paying jobs.",bullets:["Invest in advanced manufacturing and rural small businesses","Expand ports, broadband, roads, and clean-energy capacity","Tie public incentives to wages, apprenticeships, and local hiring"],detail:"Kamala will partner with employers, labor, educators, and local leaders to compete for the industries of the future while making it easier to start, grow, and keep a business in Lincoln."},
  {id:"education",icon:"✦",title:"Education and Workforce Development",summary:"Every student should graduate ready for college, a career, or both.",policy:"Guarantee every high-school student access to a career credential, apprenticeship, or college-credit pathway.",bullets:["Raise teacher pay and strengthen classroom support","Modernize career and technical education","Make community college and training more affordable"],detail:"The plan connects schools with regional employers, expands paid apprenticeships, and puts literacy, attendance, and classroom excellence back at the center of state policy."},
  {id:"rights",icon:"◆",title:"Civil Rights and Equal Protection",summary:"Rights mean little unless government is prepared to defend them.",policy:"Establish the strongest state civil-rights enforcement division in Lincoln history.",bullets:["Defend voting access and reproductive freedom","Confront discrimination in housing, work, and education","Protect disability rights and equal access to public services"],detail:"As United States Attorney, Kamala has enforced civil-rights law without fear or favor. As governor, she will make equal protection a working promise in every agency and every county."},
  {id:"health",icon:"✚",title:"Healthcare and Family Security",summary:"No family should face ruin because a child gets sick or a parent needs care.",policy:"Cap essential prescription costs and expand access to neighborhood and rural clinics.",bullets:["Defend coverage for preexisting conditions","Grow the behavioral-health workforce","Support paid family leave and affordable childcare"],detail:"Kamala will use the state’s purchasing power to lower costs, protect patients from surprise bills, and bring care closer to people through clinics, telehealth, and a stronger health workforce."},
  {id:"budgets",icon:"▥",title:"Responsible Budgets and Effective Administration",summary:"Government should be disciplined, capable, and focused on results.",policy:"Require performance audits for major agencies and publish a public results dashboard.",bullets:["Balance long-term investments with fiscal discipline","Consolidate outdated systems and duplicate services","Measure outcomes—not press releases"],detail:"A Harris administration will set clear goals, modernize state technology, protect the rainy-day fund, and make every major program prove that it delivers value for Lincoln taxpayers."}
];

const news: News[] = [
  {id:"announcement",date:"JULY 8, 2026",category:"Campaign News",title:"Kamala Harris Announces Campaign for Governor of Lincoln",excerpt:"United States Attorney Kamala Harris launched a statewide campaign built on justice, opportunity, and leadership that delivers.",body:["Standing with families, educators, small-business owners, and public servants, Kamala Harris announced her campaign for Governor of Lincoln today.","“Lincoln is ready for leadership that understands both the power and the limits of public office,” Harris said. “We can keep people safe, protect their rights, grow opportunity, and restore confidence in state government. That is the work—and I am ready to lead it.”","The campaign will begin with a twelve-county listening tour focused on public safety, jobs, schools, healthcare, and honest government."]},
  {id:"integrity-plan",date:"JULY 6, 2026",category:"Policy",title:"Harris Unveils Public Integrity Plan",excerpt:"A comprehensive agenda to expose conflicts, protect whistleblowers, and hold every public official to the same standard.",body:["Kamala Harris released a public-integrity plan that would establish an independent enforcement office, strengthen disclosure rules, and create a searchable public-contracting portal.","The proposal reflects Harris’s record confronting abuse of power as United States Attorney and her commitment to a government that earns public trust every day."]},
  {id:"safer-communities",date:"JULY 2, 2026",category:"Public Safety",title:"Harris Calls for Safer Communities and Equal Justice",excerpt:"The Safe Communities Partnership will pair focused enforcement with prevention, transparency, and support for victims.",body:["At a roundtable with police chiefs, survivors, youth advocates, and neighborhood leaders, Harris outlined a balanced plan to reduce violence and strengthen trust.","The plan prioritizes proven local partnerships, modern emergency response, constitutional policing, and dependable services for crime victims."]},
  {id:"education-agenda",date:"JUNE 28, 2026",category:"Policy",title:"Harris Releases Education and Workforce Agenda",excerpt:"A new promise to connect every student with a credential, apprenticeship, or college-credit pathway.",body:["The Harris education agenda invests in teachers, literacy, career and technical education, and paid apprenticeships.","It would bring educators and employers together region by region so students can see a clear path from classroom learning to a family-sustaining career."]},
  {id:"endorsements",date:"JUNE 24, 2026",category:"Endorsements",title:"Harris Earns Major Endorsements Across Lincoln",excerpt:"Civic, labor, education, and public-safety leaders point to Harris’s independence and proven executive judgment.",body:["A growing coalition of leaders from across Lincoln endorsed Kamala Harris for governor today.","Supporters highlighted her record enforcing the law fairly, defending constitutional rights, and building durable partnerships across political and geographic lines."]},
  {id:"rural-tour",date:"JUNE 20, 2026",category:"On the Trail",title:"Harris Tours Rural Counties in Statewide Listening Tour",excerpt:"Stops with farmers, nurses, educators, and local employers put rural priorities at the center of the campaign.",body:["Kamala Harris concluded the first leg of her statewide listening tour with community conversations in four rural counties.","Residents raised access to healthcare, farm costs, roads, broadband, and keeping young people close to home—priorities Harris said will shape her first budget as governor."]}
];

const endorsements = [
  {name:"Mayor Elena Torres",title:"Mayor of Capital City",group:"Elected Officials",quote:"Kamala has the judgment to make hard decisions and the integrity to explain them. She will be a governor for every community in Lincoln.",initials:"ET"},
  {name:"Sheriff David Cole",title:"Madison County Sheriff",group:"Public Safety",quote:"She understands that safety, trust, and constitutional policing reinforce one another. That is the leadership this moment requires.",initials:"DC"},
  {name:"Dr. Amina Patel",title:"President, Lincoln Teachers Alliance",group:"Educators",quote:"Kamala listens, studies the facts, and stays focused on results for students and families.",initials:"AP"},
  {name:"Marcus Green",title:"President, State Building Trades Council",group:"Labor",quote:"Her jobs plan respects work, rewards skill, and makes sure Lincoln builds Lincoln.",initials:"MG"},
  {name:"Rev. Claire Jackson",title:"Chair, Faith & Civic Partnership",group:"Community Leaders",quote:"Kamala brings moral clarity without empty promises—and the experience to turn principle into progress.",initials:"CJ"},
  {name:"Senator Thomas Reed",title:"Lincoln State Senate, District 14",group:"Elected Officials",quote:"She is independent, prepared, and unafraid to hold power accountable.",initials:"TR"}
];

const events = [
  {day:"14",month:"JUL",time:"6:30 PM",type:"Town Hall",region:"Central",title:"A Conversation on Safe Communities",place:"Roosevelt Community Center · Capital City",desc:"Join Kamala, local leaders, and families for a conversation about safety, trust, and equal justice."},
  {day:"18",month:"JUL",time:"12:00 PM",type:"Meet & Greet",region:"North",title:"Lunch with Kamala in Oakridge",place:"Oakridge Union Hall · Oakridge",desc:"A casual community lunch focused on jobs, schools, and the future of northern Lincoln."},
  {day:"22",month:"JUL",time:"5:30 PM",type:"Organizing",region:"East",title:"East County Volunteer Kickoff",place:"Civic Arts Annex · Fairview",desc:"Meet your regional organizing team and learn how to canvass, phone bank, and host a neighborhood event."},
  {day:"27",month:"JUL",time:"7:00 PM",type:"Rally",region:"South",title:"Justice & Opportunity Rally",place:"Riverfront Pavilion · Mason",desc:"Bring your family and friends for an evening rally with Kamala and community guests."},
  {day:"03",month:"AUG",time:"6:00 PM",type:"Reception",region:"West",title:"Leadership for Lincoln Reception",place:"The Foundry · Westport",desc:"A fundraising reception supporting the campaign’s statewide field program."}
];

const record = [
  ["Constitutional Rights","Defended voting access, due process, and equal protection in cases with statewide consequences."],
  ["Unlawful Detention","Challenged detention practices that violated federal standards and demanded lasting reforms."],
  ["Public Corruption","Built complex cases against officials who traded public trust for personal advantage."],
  ["Civil Rights","Expanded enforcement against discrimination in housing, employment, and public services."],
  ["Accountability","Held powerful institutions to the same rules that apply to every family and small business."],
  ["Equal Justice","Modernized prosecution standards while strengthening services for victims and witnesses."]
];

function useRoute(){
  const [route,setRoute]=useState(typeof window === "undefined" ? "/" : window.location.pathname);
  useEffect(()=>{ const p=()=>setRoute(window.location.pathname); window.addEventListener("popstate",p); return()=>window.removeEventListener("popstate",p); },[]);
  const go=(path:string)=>{ window.history.pushState({},"",path); setRoute(path); window.scrollTo({top:0,behavior:"smooth"}); };
  return {route,go};
}

function Button({children,onClick,kind="blue",type="button"}:{children:React.ReactNode;onClick?:()=>void;kind?:"blue"|"red"|"white"|"outline";type?:"button"|"submit"}){
  return <button type={type} onClick={onClick} className={`btn btn-${kind}`}>{children}</button>;
}

function Header({route,go}:{route:string;go:(p:string)=>void}){
  const [open,setOpen]=useState(false);
  return <>
    <div className="utility"><div className="shell utility-inner"><span>Official Campaign Website</span><div><button onClick={()=>go("/involved")}>Volunteer</button><button onClick={()=>go("/contact")}>Contact</button><button>Español</button></div></div></div>
    <header className="masthead">
      <div className="rays" />
      <div className="shell brand-row">
        <button className="brand" onClick={()=>go("/")} aria-label="Kamala Harris home"><span className="brand-kamala">Kamala</span><strong>HARRIS</strong><span className="brand-office"><i/> FOR GOVERNOR OF LINCOLN <i/></span></button>
        <div className="slogan">JUSTICE <b>•</b> OPPORTUNITY <b>•</b> LEADERSHIP</div>
        <button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu"><span/><span/><span/></button>
      </div>
    </header>
    <nav className={`mainnav ${open?"open":""}`}><div className="shell nav-inner">{nav.map(([label,path])=><button key={path} className={route===path?"active":""} onClick={()=>{go(path);setOpen(false)}}>{label}</button>)}<button className="nav-donate" onClick={()=>{go("/donate");setOpen(false)}}>DONATE</button></div></nav>
  </>;
}

function SectionTitle({eyebrow,title,light=false}:{eyebrow?:string;title:string;light?:boolean}){return <div className={`section-title ${light?"light":""}`}>{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2><i/></div>}

function Signup({compact=false}:{compact?:boolean}){
  const [done,setDone]=useState(false); const [email,setEmail]=useState("");
  function submit(e:FormEvent){e.preventDefault();if(email.includes("@"))setDone(true)}
  if(done)return <div className="success">✓ You’re on the team. Watch your inbox for campaign updates.</div>;
  return <form className={compact?"signup compact":"signup"} onSubmit={submit}><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" aria-label="Email address"/><input required placeholder="ZIP code" inputMode="numeric" aria-label="ZIP code"/><Button type="submit" kind="red">JOIN US</Button></form>
}

function ActionRail({go}:{go:(p:string)=>void}){return <aside className="action-rail">
  <div className="rail-card action-card"><h3>TAKE ACTION</h3><Button kind="red" onClick={()=>go("/donate")}>DONATE TODAY <span>›</span></Button><div className="action-grid"><button onClick={()=>go("/involved")}><b>✦</b><span>JOIN THE TEAM</span></button><button onClick={()=>go("/involved")}><b>⌂</b><span>HOST AN EVENT</span></button><button onClick={()=>go("/involved")}><b>✋</b><span>VOLUNTEER</span></button><button onClick={()=>go("/involved")}><b>◎</b><span>GET A YARD SIGN</span></button></div></div>
  <div className="rail-card"><h3>CAMPAIGN UPDATES</h3><p>Get the latest from the trail.</p><Signup compact/></div>
  <div className="rail-card"><h3>UPCOMING EVENT</h3><div className="mini-event"><b>JUL 14</b><div><strong>A Conversation on Safe Communities</strong><span>Capital City · 6:30 PM</span></div></div><button className="text-link" onClick={()=>go("/events")}>SEE ALL EVENTS →</button></div>
  <div className="rail-card endorsement-mini"><h3>IN THEIR WORDS</h3><blockquote>“Kamala has the judgment to make hard decisions—and the integrity to explain them.”</blockquote><span>— Mayor Elena Torres</span></div>
  </aside>}

function Hero({go}:{go:(p:string)=>void}){return <section className="hero">
  <div className="hero-photo" aria-label="Kamala Harris"><img src="/campaign-reference.png" alt="Kamala Harris speaking outside a civic building"/></div>
  <div className="hero-shade"/>
  <div className="hero-content"><span className="hero-kicker">A GOVERNOR FOR ALL OF LINCOLN</span><h1>Justice for every family.<br/><em>Opportunity</em> in every county.</h1><p>Kamala Harris has spent her career enforcing the law, defending constitutional rights, and holding power accountable. Now she’s running to deliver serious, effective leadership for Lincoln.</p><div className="hero-actions"><Button kind="red" onClick={()=>go("/donate")}>DONATE</Button><Button kind="white" onClick={()=>go("/involved")}>JOIN THE CAMPAIGN</Button><Button kind="outline" onClick={()=>go("/issues")}>READ THE PLATFORM</Button></div></div>
  </section>}

function Home({go}:{go:(p:string)=>void}){return <>
  <div className="shell framed"><div className="main-col"><Hero go={go}/><section className="letter"><div className="letter-mark">KH</div><div><SectionTitle eyebrow="A MESSAGE FROM KAMALA" title="Lincoln is ready to lead."/><p>For as long as I have served as United States Attorney, I have believed that public office is a public trust. The law must protect people—not power. Government must open doors—not guard them for the well connected.</p><p>I’m running for governor because Lincoln can be safer, fairer, stronger, and better prepared for what comes next. Together, we will defend our rights, create opportunity in every county, and build a government worthy of the people it serves.</p><span className="signature">Kamala Harris</span></div></section>
  <section className="record-preview"><SectionTitle eyebrow="PROVEN LEADERSHIP" title="A record of standing up—and delivering."/><div className="record-grid">{record.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><Button onClick={()=>go("/record")}>EXPLORE KAMALA’S RECORD</Button></section>
  <section className="issues-preview"><SectionTitle eyebrow="THE PLAN FOR LINCOLN" title="Principle. Policy. Progress." light/><div className="issue-strip">{issues.slice(0,4).map(x=><button key={x.id} onClick={()=>go(`/issues#${x.id}`)}><b>{x.icon}</b><span>{x.title}</span><i>LEARN MORE →</i></button>)}</div><Button kind="white" onClick={()=>go("/issues")}>VIEW THE FULL PLATFORM</Button></section>
  <section className="news-preview"><div className="title-row"><SectionTitle eyebrow="FROM THE CAMPAIGN" title="Latest news"/><button className="text-link" onClick={()=>go("/news")}>VIEW ALL NEWS →</button></div><article className="lead-story"><div className="news-art"><span>ON THE TRAIL</span><div className="podium">KAMALA<br/><b>HARRIS</b></div></div><div><small>{news[0].date} · {news[0].category}</small><h3>{news[0].title}</h3><p>{news[0].excerpt}</p><button className="read-more" onClick={()=>go(`/news/${news[0].id}`)}>READ THE STORY →</button></div></article><div className="news-list">{news.slice(1,4).map(n=><button key={n.id} onClick={()=>go(`/news/${n.id}`)}><small>{n.date} · {n.category}</small><strong>{n.title}</strong><span>{n.excerpt}</span></button>)}</div></section>
  <section className="events-preview"><div className="title-row"><SectionTitle eyebrow="ON THE TRAIL" title="Meet Kamala near you."/><button className="text-link" onClick={()=>go("/events")}>ALL EVENTS →</button></div>{events.slice(0,3).map(e=><EventRow key={e.title} event={e}/>)}</section>
  <section className="endorsement-preview"><SectionTitle eyebrow="A GROWING COALITION" title="Leaders across Lincoln are with Kamala." light/><div className="quote-feature"><div className="avatar">ET</div><blockquote>“{endorsements[0].quote}”<cite>{endorsements[0].name}<span>{endorsements[0].title}</span></cite></blockquote></div><Button kind="white" onClick={()=>go("/endorsements")}>SEE THE COALITION</Button></section>
  </div><ActionRail go={go}/></div>
  <JoinBand go={go}/>
  </>}

function PageHero({eyebrow,title,desc}:{eyebrow:string;title:string;desc:string}){return <section className="page-hero"><div className="shell"><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div></section>}
function PageWrap({children,rail=true,go}:{children:React.ReactNode;rail?:boolean;go:(p:string)=>void}){return <div className={`shell page-wrap ${rail?"with-rail":""}`}><main>{children}</main>{rail&&<ActionRail go={go}/>}</div>}

function About({go}:{go:(p:string)=>void}){return <><PageHero eyebrow="MEET KAMALA" title="A lifetime of service. A leader for this moment." desc="Kamala Harris has spent her career making government answer to the people—and ensuring the law protects everyone equally."/><PageWrap go={go}><section className="prose intro"><span className="dropcap">K</span><p>amala Harris learned early that justice is not an abstract promise. It is whether a family feels safe on its block. Whether a worker gets a fair chance. Whether a person without power can still be heard.</p><p>As United States Attorney, she has led complex public-corruption and civil-rights cases, challenged unlawful government action, and built partnerships that made communities safer while respecting constitutional rights. Her approach is steady and exacting: follow the facts, know the law, listen to the people affected, and deliver a result that lasts.</p></section><div className="quote-callout">“Public office is not a prize. It is a responsibility—to protect rights, expand opportunity, and make institutions worthy of the people they serve.”<span>— Kamala Harris</span></div><SectionTitle eyebrow="SERVICE & LEADERSHIP" title="The road to this campaign"/><div className="timeline">{[["1998","Begins public-service career, prosecuting violent crime and fraud while advocating stronger victim support."],["2006","Leads a citywide justice office and introduces modern standards for accountability and case review."],["2018","Confirmed as United States Attorney, pledging independent enforcement and constitutional leadership."],["2021","Launches a civil-rights enforcement initiative focused on housing, voting access, and equal protection."],["2024","Secures landmark public-corruption convictions and comprehensive ethics reforms."],["2026","Announces campaign for Governor of Lincoln to bring competent, accountable leadership statewide."]].map(([y,t])=><div key={y}><b>{y}</b><p>{t}</p></div>)}</div><SectionTitle eyebrow="WHY SHE’S RUNNING" title="Lincoln can expect more."/><div className="two-col prose"><p>Families are working harder and still wondering whether government can meet the moment. Too many communities have been asked to choose between safety and fairness, growth and responsibility, ambition and competence. Kamala rejects those false choices.</p><p>She is running to build a state government that enforces the law, defends freedom, invests in people, and manages public resources with discipline. A government that remembers who it works for—and gets results in every county.</p></div></PageWrap></>}

function Record({go}:{go:(p:string)=>void}){const [open,setOpen]=useState(0);return <><PageHero eyebrow="THE RECORD" title="Tested by hard cases. Guided by the Constitution." desc="As United States Attorney, Kamala Harris has taken on powerful interests, defended civil rights, and delivered results with independence and discipline."/><PageWrap go={go}><div className="stats"><div><strong>18</strong><span>Public integrity convictions</span></div><div><strong>42</strong><span>Civil-rights actions resolved</span></div><div><strong>$186M</strong><span>Recovered for taxpayers & victims</span></div></div><SectionTitle eyebrow="SERIOUS WORK. REAL RESULTS." title="Accountability without fear or favor."/><div className="record-details">{[
  ["Justice and public safety","Kamala reorganized violent-crime and victim-services teams around measurable outcomes, regional coordination, and constitutional standards.",["Expanded survivor and witness support","Created cross-county firearms-trafficking task force","Established transparent case-review protocols"]],
  ["Constitutional leadership","When executive power crossed legal limits, Kamala acted—regardless of politics or pressure.",["Challenged unlawful detention practices","Defended access to the ballot","Issued public constitutional-compliance guidance"]],
  ["Civil rights enforcement","Kamala rebuilt civil-rights enforcement into a proactive statewide force.",["Secured housing and workplace discrimination settlements","Protected access for people with disabilities","Created rapid response for threats against houses of worship"]],
  ["Anti-corruption work","Her office followed money, records, and evidence to expose schemes that betrayed public trust.",["Prosecuted procurement and contracting fraud","Recovered misused public funds","Strengthened protections for cooperating witnesses"]],
  ["Protecting the public interest","Kamala has insisted that enforcement serve people—not headlines.",["Recovered funds for families and taxpayers","Pursued corporate fraud and predatory practices","Partnered with local officials on durable reforms"]]
].map((x,i)=><div className={`record-accordion ${open===i?"expanded":""}`} key={x[0] as string}><button onClick={()=>setOpen(open===i?-1:i)}><span>0{i+1}</span><strong>{x[0] as string}</strong><b>{open===i?"−":"+"}</b></button>{open===i&&<div><p>{x[1] as string}</p><ul>{(x[2] as string[]).map(y=><li key={y}>{y}</li>)}</ul></div>}</div>)}</div><div className="quote-callout navy">“The measure of enforcement is not how loudly government speaks. It is whether the law is applied fairly, rights are protected, and people are safer.”<span>— Kamala Harris</span></div></PageWrap></>}

function Issues({go}:{go:(p:string)=>void}){const [active,setActive]=useState("safety");useEffect(()=>{const hash=window.location.hash.slice(1);if(issues.some(i=>i.id===hash))setActive(hash)},[]);const current=issues.find(i=>i.id===active)!;return <><PageHero eyebrow="THE HARRIS PLAN" title="A stronger Lincoln—built to last." desc="Practical plans grounded in values: safe communities, honest government, good jobs, excellent schools, secure families, and equal rights."/><PageWrap go={go} rail={false}><div className="issue-layout"><aside className="issue-tabs">{issues.map(i=><button key={i.id} className={active===i.id?"active":""} onClick={()=>{setActive(i.id);history.replaceState({},"",`/issues#${i.id}`)}}><b>{i.icon}</b>{i.title}</button>)}</aside><article className="issue-detail"><span className="big-icon">{current.icon}</span><small>THE HARRIS PLAN</small><h2>{current.title}</h2><p className="lede">{current.summary}</p><div className="key-policy"><span>KEY POLICY</span><strong>{current.policy}</strong></div><h3>What Kamala will do</h3><ul>{current.bullets.map(b=><li key={b}>{b}</li>)}</ul><h3>The plan</h3><p>{current.detail}</p><div className="issue-actions"><Button kind="red" onClick={()=>go("/involved")}>HELP BUILD THIS PLAN</Button><Button kind="outline">DOWNLOAD FACT SHEET</Button></div></article></div></PageWrap></>}

function NewsPage({go}:{go:(p:string)=>void}){return <><PageHero eyebrow="NEWSROOM" title="News from the campaign" desc="Policy announcements, campaign updates, and dispatches from across Lincoln."/><PageWrap go={go}><div className="filter-pills"><button className="active">All</button><button>Campaign News</button><button>Policy</button><button>On the Trail</button></div><div className="article-grid">{news.map((n,i)=><article className={i===0?"featured":""} key={n.id}><div className="article-img"><span>{n.category}</span><b>{i===0?"KAMALA HARRIS":"KH"}</b></div><small>{n.date} · {n.category}</small><h2>{n.title}</h2><p>{n.excerpt}</p><button className="read-more" onClick={()=>go(`/news/${n.id}`)}>READ MORE →</button></article>)}</div></PageWrap></>}
function Article({post,go}:{post:News;go:(p:string)=>void}){return <><PageHero eyebrow={`${post.category} · ${post.date}`} title={post.title} desc={post.excerpt}/><PageWrap go={go}><article className="article-body"><button className="back" onClick={()=>go("/news")}>← BACK TO NEWS</button>{post.body.map(p=><p key={p}>{p}</p>)}<div className="share"><strong>SHARE THIS STORY</strong><button>f</button><button>𝕏</button><button>✉</button></div></article><div className="related"><SectionTitle eyebrow="KEEP READING" title="More from the campaign"/>{news.filter(n=>n.id!==post.id).slice(0,2).map(n=><button key={n.id} onClick={()=>go(`/news/${n.id}`)}><small>{n.date}</small><strong>{n.title}</strong></button>)}</div></PageWrap></>}

function Endorsements({go}:{go:(p:string)=>void}){const [filter,setFilter]=useState("All");const groups=["All","Elected Officials","Community Leaders","Labor","Public Safety","Educators"];return <><PageHero eyebrow="THE COALITION" title="Lincoln leaders trust Kamala to deliver." desc="Elected officials, educators, working people, civic voices, and public-safety leaders are joining this campaign."/><PageWrap go={go} rail={false}><div className="featured-endorsement"><div className="large-avatar">ET</div><div><span>FEATURED ENDORSEMENT</span><blockquote>“{endorsements[0].quote}”</blockquote><strong>{endorsements[0].name}</strong><small>{endorsements[0].title}</small></div></div><div className="filter-pills center">{groups.map(g=><button className={g===filter?"active":""} onClick={()=>setFilter(g)} key={g}>{g}</button>)}</div><div className="endorsement-grid">{endorsements.filter(e=>filter==="All"||e.group===filter).map(e=><article key={e.name}><div className="avatar">{e.initials}</div><span>{e.group}</span><h3>{e.name}</h3><small>{e.title}</small><blockquote>“{e.quote}”</blockquote></article>)}</div><div className="endorse-cta"><h2>Add your name.</h2><p>Join thousands of Lincoln voters endorsing Kamala Harris for governor.</p><Button kind="red" onClick={()=>go("/involved")}>ENDORSE KAMALA</Button></div></PageWrap></>}

function EventRow({event:e}:{event:typeof events[0]}){const [rsvp,setRsvp]=useState(false);return <article className="event-row"><div className="event-date"><b>{e.day}</b><span>{e.month}</span></div><div className="event-info"><small>{e.type} · {e.region} Lincoln · {e.time}</small><h3>{e.title}</h3><span>{e.place}</span><p>{e.desc}</p></div><Button kind={rsvp?"blue":"red"} onClick={()=>setRsvp(true)}>{rsvp?"✓ YOU’RE ON THE LIST":"RSVP"}</Button></article>}
function Events({go}:{go:(p:string)=>void}){const [region,setRegion]=useState("All");return <><PageHero eyebrow="ON THE TRAIL" title="Come meet Kamala." desc="This campaign is built face to face, block by block, county by county. Find an event near you."/><PageWrap go={go}><div className="event-filter"><label>FILTER BY REGION<select value={region} onChange={e=>setRegion(e.target.value)}><option>All</option><option>Central</option><option>North</option><option>East</option><option>South</option><option>West</option></select></label><span>{events.filter(e=>region==="All"||e.region===region).length} UPCOMING EVENTS</span></div>{events.filter(e=>region==="All"||e.region===region).map(e=><EventRow key={e.title} event={e}/>)}</PageWrap></>}

function Media({go}:{go:(p:string)=>void}){return <><PageHero eyebrow="MEDIA CENTER" title="Resources for the press and public" desc="Campaign releases, photography, video, speeches, and background materials from Kamala Harris for Governor."/><PageWrap go={go}><SectionTitle eyebrow="LATEST RELEASES" title="From the press office"/><div className="press-list">{news.slice(0,4).map(n=><button key={n.id} onClick={()=>go(`/news/${n.id}`)}><span>{n.date}</span><strong>{n.title}</strong><i>VIEW RELEASE →</i></button>)}</div><SectionTitle eyebrow="PHOTOS & VIDEO" title="From the trail"/><div className="media-grid"><div className="media-tile large"><span>▶</span><strong>Campaign Launch: A Governor for All of Lincoln</strong><small>2:14</small></div>{["Listening in rural Lincoln","Safe Communities roundtable","Meeting Lincoln educators"].map((x,i)=><div className="media-tile" key={x}><span>{i===0?"▣":"▶"}</span><strong>{x}</strong><small>{i===0?"24 PHOTOS":"WATCH VIDEO"}</small></div>)}</div><SectionTitle eyebrow="DOWNLOADS" title="Press kit"/><div className="download-grid"><button><b>PDF</b><span><strong>Candidate Biography</strong><small>Updated July 2026 · 248 KB</small></span>↓</button><button><b>ZIP</b><span><strong>Official Campaign Photography</strong><small>12 high-resolution images · 38 MB</small></span>↓</button><button><b>PDF</b><span><strong>Campaign Brand Guide</strong><small>Logos and usage · 1.2 MB</small></span>↓</button></div><div className="press-contact"><span>PRESS CONTACT</span><h3>Lincoln Campaign Press Office</h3><p>press@kamalaforlincoln.com · (555) 014-2026</p><small>For deadline requests, please include your outlet and publication time.</small></div></PageWrap></>}

function FormSuccess({children}:{children:string}){return <div className="form-success"><b>✓</b><h3>Thank you.</h3><p>{children}</p></div>}
function Involved({go}:{go:(p:string)=>void}){const [done,setDone]=useState(false);const [interests,setInterests]=useState<string[]>([]);const opts=["Canvassing","Phone banking","Digital organizing","Host an event","Yard sign","Endorse Kamala"];return <><PageHero eyebrow="GET INVOLVED" title="This campaign needs you." desc="The conversations you have—with a neighbor, coworker, or friend—will decide this election. Choose how you want to help."/><PageWrap go={go} rail={false}>{done?<FormSuccess>You’re officially part of Team Kamala. A local organizer will be in touch soon.</FormSuccess>:<form className="volunteer-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><div className="form-intro"><h2>Join Team Kamala</h2><p>Tell us a little about yourself and how you’d like to help. No experience needed—just a belief in Lincoln’s future.</p></div><div className="form-grid"><label>FIRST NAME<input required/></label><label>LAST NAME<input required/></label><label>EMAIL<input required type="email"/></label><label>MOBILE PHONE<input required type="tel"/></label><label>ZIP CODE<input required inputMode="numeric"/></label><label>COUNTY<input/></label></div><fieldset><legend>I’M INTERESTED IN</legend><div className="interest-grid">{opts.map(o=><label className={interests.includes(o)?"selected":""} key={o}><input type="checkbox" checked={interests.includes(o)} onChange={()=>setInterests(interests.includes(o)?interests.filter(x=>x!==o):[...interests,o])}/><b>{o==="Canvassing"?"⌂":o==="Phone banking"?"☎":o==="Digital organizing"?"◎":o==="Host an event"?"★":o==="Yard sign"?"▰":"✓"}</b><span>{o}</span></label>)}</div></fieldset><label>ANYTHING ELSE WE SHOULD KNOW?<textarea rows={4} placeholder="Skills, availability, or a note for your local organizer"/></label><Button kind="red" type="submit">SIGN ME UP</Button><small className="fineprint">By submitting this form, you agree to receive campaign updates. Message and data rates may apply. Reply STOP to opt out.</small></form>}</PageWrap></>}

function Donate({go}:{go:(p:string)=>void}){const [amount,setAmount]=useState("25");const [custom,setCustom]=useState("");const [done,setDone]=useState(false);return <><PageHero eyebrow="POWER THE CAMPAIGN" title="Invest in leadership that delivers." desc="Your contribution helps organize every county, reach more voters, and build a stronger future for Lincoln."/><PageWrap go={go} rail={false}><div className="donate-layout"><section className="donate-box">{done?<FormSuccess>Your pledge has been recorded for this campaign-site demonstration.</FormSuccess>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><span className="step">STEP 1 OF 2</span><h2>Choose an amount</h2><div className="amount-grid">{["10","25","50","100","250"].map(a=><button type="button" className={amount===a?"selected":""} onClick={()=>{setAmount(a);setCustom("")}} key={a}>${a}</button>)}<label className={amount==="other"?"selected":""}>$<input value={custom} onFocus={()=>setAmount("other")} onChange={e=>setCustom(e.target.value)} placeholder="Other" inputMode="decimal"/></label></div><label className="recurring"><input type="checkbox"/> Make this a monthly contribution</label><hr/><h2>Your information</h2><div className="form-grid"><label>FIRST NAME<input required/></label><label>LAST NAME<input required/></label><label>EMAIL<input required type="email"/></label><label>PHONE<input type="tel"/></label><label className="wide">ADDRESS<input required/></label><label>CITY<input required/></label><label>ZIP CODE<input required/></label></div><Button kind="red" type="submit">CONTINUE — ${amount==="other"?(custom||"0"):amount}</Button><div className="secure">▣ SECURE DONATION · Your information is protected</div></form>}</section><aside className="donate-aside"><h3>Your support matters.</h3><p>A contribution today helps us hire organizers, open field offices, print literature, and talk directly with voters across Lincoln.</p><blockquote>“We are building this campaign the same way we will govern: with people at the center.”<span>— Kamala</span></blockquote><div className="paid-by">PAID FOR BY KAMALA HARRIS FOR GOVERNOR</div></aside></div><p className="disclaimer">Contributions or gifts to Kamala Harris for Governor are not tax deductible. State law requires political committees to report the name, mailing address, occupation, and employer of individuals whose contributions exceed reporting thresholds. This demonstration does not process payments or retain entered information.</p></PageWrap></>}

function Contact({go}:{go:(p:string)=>void}){const [done,setDone]=useState(false);return <><PageHero eyebrow="CONTACT" title="We want to hear from you." desc="Questions, ideas, press inquiries, or help getting involved—reach the right member of Team Kamala."/><PageWrap go={go}><div className="contact-cards"><article><b>⌂</b><h3>Campaign Headquarters</h3><p>214 Constitution Avenue<br/>Capital City, Lincoln 20006</p><span>(555) 014-2026</span></article><article><b>✉</b><h3>Press Office</h3><p>For reporters and media organizations.</p><span>press@kamalaforlincoln.com</span></article><article><b>✦</b><h3>Volunteer Team</h3><p>Get help with a shift or connect with an organizer.</p><span>organize@kamalaforlincoln.com</span></article></div>{done?<FormSuccess>Your message has been received. A campaign team member will follow up soon.</FormSuccess>:<form className="contact-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><h2>Send the campaign a message</h2><div className="form-grid"><label>NAME<input required/></label><label>EMAIL<input required type="email"/></label><label>PHONE<input type="tel"/></label><label>TOPIC<select><option>General question</option><option>Volunteer support</option><option>Press inquiry</option><option>Event invitation</option><option>Yard sign</option></select></label><label className="wide">MESSAGE<textarea required rows={6}/></label></div><Button kind="red" type="submit">SEND MESSAGE</Button></form>}</PageWrap></>}

function JoinBand({go}:{go:(p:string)=>void}){return <section className="join-band"><div className="shell"><div><span>READY TO BUILD A STRONGER LINCOLN?</span><h2>Join Kamala’s campaign.</h2></div><Signup/><button className="join-volunteer" onClick={()=>go("/involved")}>VOLUNTEER →</button></div></section>}
function Footer({go}:{go:(p:string)=>void}){return <footer><div className="shell footer-grid"><div className="footer-brand"><span>Kamala</span><strong>HARRIS</strong><small>FOR GOVERNOR OF LINCOLN</small><p>Justice. Opportunity. Leadership.</p></div><div><h4>EXPLORE</h4>{nav.slice(1,7).map(([l,p])=><button key={p} onClick={()=>go(p)}>{l}</button>)}</div><div><h4>TAKE ACTION</h4><button onClick={()=>go("/involved")}>Volunteer</button><button onClick={()=>go("/events")}>Attend an Event</button><button onClick={()=>go("/involved")}>Request a Yard Sign</button><button onClick={()=>go("/donate")}>Donate</button></div><div><h4>FOLLOW THE CAMPAIGN</h4><div className="socials"><button>f</button><button>𝕏</button><button>◎</button><button>▶</button></div><p>214 Constitution Avenue<br/>Capital City, Lincoln 20006</p></div></div><div className="shell footer-bottom"><span>© 2026 Kamala Harris for Governor</span><span className="paid">PAID FOR BY KAMALA HARRIS FOR GOVERNOR</span><div><button>Privacy</button><button>Accessibility</button></div></div></footer>}

export default function App(){const {route,go}=useRoute();const [showTop,setShowTop]=useState(false);useEffect(()=>{const s=()=>setShowTop(scrollY>600);addEventListener("scroll",s);return()=>removeEventListener("scroll",s)},[]);const content=useMemo(()=>{if(route==="/")return <Home go={go}/>;if(route==="/about")return <About go={go}/>;if(route==="/issues")return <Issues go={go}/>;if(route==="/record")return <Record go={go}/>;if(route==="/news")return <NewsPage go={go}/>;if(route.startsWith("/news/")){const p=news.find(n=>route===`/news/${n.id}`);return p?<Article post={p} go={go}/>:<NewsPage go={go}/>};if(route==="/endorsements")return <Endorsements go={go}/>;if(route==="/events")return <Events go={go}/>;if(route==="/media")return <Media go={go}/>;if(route==="/involved")return <Involved go={go}/>;if(route==="/donate")return <Donate go={go}/>;if(route==="/contact")return <Contact go={go}/>;return <Home go={go}/>},[route]);return <><Header route={route} go={go}/>{content}<Footer go={go}/>{showTop&&<button className="back-top" onClick={()=>scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top">↑</button>}</>}
